//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQSAdmin_WpfCustomControlLibrary {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MySetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static MySetting defaultInstance = ((MySetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySetting())));
        
        public static MySetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchProductID {
            get {
                return ((string)(this["SearchProductID"]));
            }
            set {
                this["SearchProductID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchProductName {
            get {
                return ((string)(this["SearchProductName"]));
            }
            set {
                this["SearchProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchProsuctDesc {
            get {
                return ((string)(this["SearchProsuctDesc"]));
            }
            set {
                this["SearchProsuctDesc"] = value;
            }
        }
    }
}
