//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQSAdmin_WpfCustomControlLibrary.SQSAdminWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQSAdminWCFService.ISQSAdminService")]
    public interface ISQSAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_LoadSQSGroupList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_LoadSQSGroupListResponse")]
        System.Data.DataSet SQSAdmin_StudioM_LoadSQSGroupList(string groupname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetPAGFromProduct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetPAGFromProductR" +
            "esponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetPAGFromProduct(string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetRegionGroupBySt" +
            "ate", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetRegionGroupBySt" +
            "ateResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetRegionGroupByState(int pstateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetStandardInclusi" +
            "ons", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetStandardInclusi" +
            "onsResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetStandardInclusions(int pbrandid, int pregiongroupid, int pagid, int pstateid, string productid, string productname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetSupplierBrand", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetSupplierBrandResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetSupplierBrand(string brandname, int pstateid, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditSupplierBrand", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditSupplierBrandResponse" +
            "")]
        void SQSAdmin_StudioM_AddEditSupplierBrand(int supplierbrandid, string brandname, int pstateid, int active, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_CheckSupplierBrandExists", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_CheckSupplierBrandExistsResp" +
            "onse")]
        bool SQSAdmin_StudioM_CheckSupplierBrandExists(string brandname, int pstateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_IsStandardInclusio" +
            "nExists", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_IsStandardInclusio" +
            "nExistsResponse")]
        bool SQSAdmin_StandardInclusion_IsStandardInclusionExists(int pagid, int pbrandid, int pregiongroupid, int standardinclusionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_AddEditStandardInc" +
            "lusion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_AddEditStandardInc" +
            "lusionResponse")]
        void SQSAdmin_StandardInclusion_AddEditStandardInclusion(int standardinclusionid, int pagid, int pbrandid, int pregiongroupid, decimal quantity, int active, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_RemoveStandardIncl" +
            "usion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_RemoveStandardIncl" +
            "usionResponse")]
        void SQSAdmin_StandardInclusion_RemoveStandardInclusion(int standardinclusionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetAvailableStanda" +
            "rdInclusionPAGFromMasterList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetAvailableStanda" +
            "rdInclusionPAGFromMasterListResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetAvailableStandardInclusionPAGFromMasterList(int areaid, int groupid, string productid, string productname, int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetAvailableStanda" +
            "rdInclusionPAG", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetAvailableStanda" +
            "rdInclusionPAGResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetAvailableStandardInclusionPAG(int areaid, int groupid, string productid, string productname, int pbrandid, int pregiongroupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_SaveStandardInclus" +
            "ionToBrand", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_SaveStandardInclus" +
            "ionToBrandResponse")]
        void SQSAdmin_StandardInclusion_SaveStandardInclusionToBrand(string selectedids, string brandids, int regiongroupid, string usercode, System.DateTime effectivedate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeMinimumArea_GetSourceHomeByBrand" +
            "", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeMinimumArea_GetSourceHomeByBrand" +
            "Response")]
        System.Data.DataSet SQSAdmin_HomeMinimumArea_GetSourceHomeByBrand(int brandid, string homename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeMinimumArea_GetTargetHomeByBrand" +
            "", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeMinimumArea_GetTargetHomeByBrand" +
            "Response")]
        System.Data.DataSet SQSAdmin_HomeMinimumArea_GetTargetHomeByBrand(int brandid, string homename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeMinimumArea_CopyMinimumAreasFrom" +
            "SourceHomeToTargetHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeMinimumArea_CopyMinimumAreasFrom" +
            "SourceHomeToTargetHomeResponse")]
        void SQSAdmin_HomeMinimumArea_CopyMinimumAreasFromSourceHomeToTargetHome(string sourcehomeid, string targethomeidstring, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_UploadImageToSharepointImage" +
            "Library", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_UploadImageToSharepointImage" +
            "LibraryResponse")]
        void SQSAdmin_StudioM_UploadImageToSharepointImageLibrary(string productid, int supplierid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_LoadProduct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_LoadProductResponse")]
        System.Data.DataSet SQSAdmin_RelatedArea_LoadProduct(string productid, string keyword, int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_LoadExistingAreasForProd" +
            "uct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_LoadExistingAreasForProd" +
            "uctResponse")]
        System.Data.DataSet SQSAdmin_RelatedArea_LoadExistingAreasForProduct(string productid, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_LoadAvailableAreasForPro" +
            "duct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_LoadAvailableAreasForPro" +
            "ductResponse")]
        System.Data.DataSet SQSAdmin_RelatedArea_LoadAvailableAreasForProduct(string productid, string keyword, string callfrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_AddSelectedAreasToProduc" +
            "t", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_AddSelectedAreasToProduc" +
            "tResponse")]
        void SQSAdmin_RelatedArea_AddSelectedAreasToProduct(string productid, string areaidstring, string usercode, string callfrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_RemooveSelectedAreasFrom" +
            "Product", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_RelatedArea_RemooveSelectedAreasFrom" +
            "ProductResponse")]
        void SQSAdmin_RelatedArea_RemooveSelectedAreasFromProduct(string productid, string areaidstring, string callfrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetStudioMProduct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetStudioMProductResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetStudioMProduct(int stateid, string productid, string productname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_BulkConfigureStudiomQandA", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_BulkConfigureStudiomQandARes" +
            "ponse")]
        bool SQSAdmin_StudioM_BulkConfigureStudiomQandA(string supplierbrandid, string productidstring, string questionidstring, string answeridstring, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Home_GetHomeList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Home_GetHomeListResponse")]
        System.Data.DataSet SQSAdmin_Home_GetHomeList(int stateid, int brandid, string homename, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Home_GetHomePlanByStateAndBrands", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Home_GetHomePlanByStateAndBrandsResp" +
            "onse")]
        System.Data.DataSet SQSAdmin_Home_GetHomePlanByStateAndBrands(int stateid, string brandids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAreas", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAreasResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetAreas(int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetGroups", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetGroupsResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetGroups(int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_GetAvailablePAGFor" +
            "Home", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_GetAvailablePAGFor" +
            "HomeResponse")]
        System.Data.DataSet SQSAdmin_HomeConfiguration_GetAvailablePAGForHome(int homeid, int areaid, int groupid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_GetExistingPAGForH" +
            "ome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_GetExistingPAGForH" +
            "omeResponse")]
        System.Data.DataSet SQSAdmin_HomeConfiguration_GetExistingPAGForHome(int homeid, int areaid, int groupid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_AddProductToHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_AddProductToHomeRe" +
            "sponse")]
        bool SQSAdmin_HomeConfiguration_AddProductToHome(int homeid, string selectedpagid, string qtystring, string changeqtystring, string changepricestring, string extradescstring, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_UpdatePagForHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_UpdatePagForHomeRe" +
            "sponse")]
        bool SQSAdmin_HomeConfiguration_UpdatePagForHome(int homeid, int pagid, string quantity, int changeqty, int changeprice, int extradesc, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_RemoveProductsFrom" +
            "Home", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_RemoveProductsFrom" +
            "HomeResponse")]
        bool SQSAdmin_HomeConfiguration_RemoveProductsFromHome(int homeid, string selectedpagids, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_GetProducts", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_GetProductsRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_HomeConfiguration_GetProducts(int stateid, string productid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_CopyProductConfigu" +
            "ration", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_CopyProductConfigu" +
            "rationResponse")]
        string SQSAdmin_HomeConfiguration_CopyProductConfiguration(string sourceproductid, string targetproductid, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_GetHomeModelQuant" +
            "ity", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_GetHomeModelQuant" +
            "ityResponse")]
        System.Data.DataSet SQSAdmin_QuantityManagement_GetHomeModelQuantity(string stateid, string areaid, string groupid, string brandid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_GetHomeFacadeQuan" +
            "tity", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_GetHomeFacadeQuan" +
            "tityResponse")]
        System.Data.DataSet SQSAdmin_QuantityManagement_GetHomeFacadeQuantity(string stateid, string areaid, string groupid, string brandid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_UpdateQuantityFor" +
            "AreaGroupAtHomeModel", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_UpdateQuantityFor" +
            "AreaGroupAtHomeModelResponse")]
        bool SQSAdmin_QuantityManagement_UpdateQuantityForAreaGroupAtHomeModel(string stateid, string areaid, string groupid, string brandid, string homemodel, string quantity, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_UpdateQuantityFor" +
            "AreaGroupAtHomeFacade", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_UpdateQuantityFor" +
            "AreaGroupAtHomeFacadeResponse")]
        bool SQSAdmin_QuantityManagement_UpdateQuantityForAreaGroupAtHomeFacade(string areaid, string groupid, string homeid, string quantity, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_RefreshQuantity", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_QuantityManagement_RefreshQuantityRe" +
            "sponse")]
        bool SQSAdmin_QuantityManagement_RefreshQuantity(string stateid, string areaid, string groupid, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_BulkUpdateQuantity" +
            "", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_BulkUpdateQuantity" +
            "Response")]
        bool SQSAdmin_HomeConfiguration_BulkUpdateQuantity(string homeid, string pagidstring, string quantity, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_BulkUpdateHomeMode" +
            "lQuantity", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_HomeConfiguration_BulkUpdateHomeMode" +
            "lQuantityResponse")]
        bool SQSAdmin_HomeConfiguration_BulkUpdateHomeModelQuantity(string brandid, string areaid, string groupid, string homestring, string quantity, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_SearchDisclaimers", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_SearchDisclaimersResponse")]
        System.Data.DataSet SQSAdmin_SearchDisclaimers(int typeid, int stateid, int regionid, int brandid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_SearchDisclaimer", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_SearchDisclaimerResponse")]
        string SQSAdmin_SearchDisclaimer(string type, string state, int regionid, int brandid, string brandname, System.DateTime depositDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_BasePriceHoldDays", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_BasePriceHoldDaysResponse")]
        System.Data.DataSet SQSAdmin_Generic_BasePriceHoldDays(string stateid, string regionids, string brandids, System.DateTime effectivedate, string active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_UpdateBasePriceHoldDays", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_UpdateBasePriceHoldDaysRespo" +
            "nse")]
        void SQSAdmin_Generic_UpdateBasePriceHoldDays(string id, string daysfrom, string daysto, System.DateTime effectivedate, string active, string depositamount, string usercode, decimal cmapercent, decimal surchargepercent, decimal btpsinglestorey, decimal btpdoublestorey, decimal btpSingleStoryDiscount, decimal btpDoubleStoryDiscount, decimal btpSingleStoreyCostSiteOther, decimal btpDoubleStoreyCostSiteOther);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_NeweBasePriceHoldDays", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_NeweBasePriceHoldDaysRespons" +
            "e")]
        void SQSAdmin_Generic_NeweBasePriceHoldDays(
                    int stateid, 
                    string regionids, 
                    string brandids, 
                    string daysfrom, 
                    string daysto, 
                    System.DateTime effectivedate, 
                    string active, 
                    string depositamount, 
                    string usercode, 
                    string cmapercent, 
                    string surchargepercent, 
                    string regionalsurchargeSSpercent, 
                    string regionalsurchargeSDpercent, 
                    string btpSingleStoryDiscount, 
                    string btpDoubleStoryDiscount, 
                    string btpSingleStoreyCostSiteOther, 
                    string btpDoubleStoreyCostSiteOther);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_SaveDisclaimer", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_SaveDisclaimerResponse")]
        string SQSAdmin_SaveDisclaimer(string type, string state, string regionids, string brandids, string disclaimerText, string internalNotes, string effectiveDate, int status, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetState", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetStateResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetRegionList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetRegionListResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetRegionList(int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAllAreas", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAllAreasResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetAllAreas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAllGroups", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAllGroupsResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetAllGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetGroupsFromArea", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetGroupsFromAreaResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetGroupsFromArea(int areaid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetBrandByState", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetBrandByStateResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetBrandByState(int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetHomeNameBySearch", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetHomeNameBySearchResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetHomeNameBySearch(int stateid, int brandid, string homename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetSQSConfiguration", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetSQSConfigurationResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetSQSConfiguration(string configCode, string codeValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetSpecificationByStateRegio" +
            "nsBrands", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetSpecificationByStateRegio" +
            "nsBrandsResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetSpecificationByStateRegionsBrands(int stateid, string regionids, string brandids, System.DateTime effdate, string systemid, string attachmentid, string homestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetSpecificationByStateRegio" +
            "nBrand", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetSpecificationByStateRegio" +
            "nBrandResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetSpecificationByStateRegionBrand(int stateid, int regionid, int brandid, System.DateTime effdate, string systemid, string attachmentid, string homestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_SaveSpecificationByStateRegi" +
            "onBrand", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_SaveSpecificationByStateRegi" +
            "onBrandResponse")]
        void SQSAdmin_Generic_SaveSpecificationByStateRegionBrand(int id, string filename, int stateid, int regionid, int brandid, int homeid, System.DateTime effdate, int systemformid, int attachmenttypeid, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAvailabeAreasByHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAvailabeAreasByHomeRespon" +
            "se")]
        System.Data.DataSet SQSAdmin_Generic_GetAvailabeAreasByHome(int homeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetConfiguredAreasByHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetConfiguredAreasByHomeResp" +
            "onse")]
        System.Data.DataSet SQSAdmin_Generic_GetConfiguredAreasByHome(int homeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_AddMinimumAreasToHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_AddMinimumAreasToHomeRespons" +
            "e")]
        void SQSAdmin_Generic_AddMinimumAreasToHome(int homeid, string selectedareaid, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_RemoveMinimumAreasFromHome", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_RemoveMinimumAreasFromHomeRe" +
            "sponse")]
        void SQSAdmin_Generic_RemoveMinimumAreasFromHome(int homeid, string selectedareaid, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAvailablePAGByState", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetAvailablePAGByStateRespon" +
            "se")]
        System.Data.DataSet SQSAdmin_Generic_GetAvailablePAGByState(string stateid, string areaid, string groupid, string keyword, string pagid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetDisplayHomeByPAGAndState", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetDisplayHomeByPAGAndStateR" +
            "esponse")]
        System.Data.DataSet SQSAdmin_Generic_GetDisplayHomeByPAGAndState(string stateid, string brandid, string pagid, string displayhomename, string suburb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ReplaceDisplayHomePAG", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ReplaceDisplayHomePAGRespons" +
            "e")]
        string SQSAdmin_Generic_ReplaceDisplayHomePAG(string existingpagid, string newpagid, string displayhomeid, string usercode, string qty, string changeqty, string changeprice, string allowdesc, string desc, string newextradesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductUOM", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductUOMResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetProductUOM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductCategory", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductCategoryResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetProductCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductCode", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductCodeResponse")]
        System.Data.DataSet SQSAdmin_Generic_GetProductCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductDisplayCode", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductDisplayCodeRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_Generic_GetProductDisplayCode(string forpromo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductCostCenterCode", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_GetProductCostCenterCodeResp" +
            "onse")]
        System.Data.DataSet SQSAdmin_Generic_GetProductCostCenterCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportProduct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportProductResponse")]
        System.Data.DataSet SQSAdmin_Generic_ImportProduct(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportPriceVerticalFormat", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportPriceVerticalFormatRes" +
            "ponse")]
        System.Data.DataSet SQSAdmin_Generic_ImportPriceVerticalFormat(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportPriceHorizontalFormat", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportPriceHorizontalFormatR" +
            "esponse")]
        System.Data.DataSet SQSAdmin_Generic_ImportPriceHorizontalFormat(System.Data.DataTable dt, string usercode, string stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportPriceHorizontalFormatN" +
            "SW", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportPriceHorizontalFormatN" +
            "SWResponse")]
        System.Data.DataSet SQSAdmin_Generic_ImportPriceHorizontalFormatNSW(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportQuantity", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ImportQuantityResponse")]
        System.Data.DataSet SQSAdmin_Generic_ImportQuantity(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_CheckExistingProducts", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_CheckExistingProductsRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_Generic_CheckExistingProducts(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidatePriceVerticalFormat", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidatePriceVerticalFormatR" +
            "esponse")]
        System.Data.DataSet SQSAdmin_Generic_ValidatePriceVerticalFormat(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidatePriceHorizontalForma" +
            "t", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidatePriceHorizontalForma" +
            "tResponse")]
        System.Data.DataSet SQSAdmin_Generic_ValidatePriceHorizontalFormat(System.Data.DataTable dt, string usercode, string stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidatePriceHorizontalForma" +
            "tNSW", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidatePriceHorizontalForma" +
            "tNSWResponse")]
        System.Data.DataSet SQSAdmin_Generic_ValidatePriceHorizontalFormatNSW(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidateQuantity", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Generic_ValidateQuantityResponse")]
        System.Data.DataSet SQSAdmin_Generic_ValidateQuantity(System.Data.DataTable dt, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionListResponse")]
        System.Data.DataSet SQSAdmin_Promotion_GetPromotionList(int stateid, int brandid, int storey, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionTypeList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionTypeListRespon" +
            "se")]
        System.Data.DataSet SQSAdmin_Promotion_GetPromotionTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_UpdateMultiplePromotionNam" +
            "e", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_UpdateMultiplePromotionNam" +
            "eResponse")]
        bool SQSAdmin_Promotion_UpdateMultiplePromotionName(string promotionid, string promotionname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_CheckMasterPromotionProduc" +
            "tExist", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_CheckMasterPromotionProduc" +
            "tExistResponse")]
        bool SQSAdmin_Promotion_CheckMasterPromotionProductExist(int stateid, string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_CheckMultiplePromotionExis" +
            "t", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_CheckMultiplePromotionExis" +
            "tResponse")]
        bool SQSAdmin_Promotion_CheckMultiplePromotionExist(int brandid, int stories, string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_SavePromotion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_SavePromotionResponse")]
        void SQSAdmin_Promotion_SavePromotion(int stateid, int brandid, int storey, int promotiontypeid, string productid, string promotionname, decimal promotioncost, decimal capevalue, int forregional, int active, int displaycodeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionDetails", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionDetailsRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_Promotion_GetPromotionDetails(int multiplepromotionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetAvailableProductsForPro" +
            "motion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetAvailableProductsForPro" +
            "motionResponse")]
        System.Data.DataSet SQSAdmin_Promotion_GetAvailableProductsForPromotion(int multiplepromotionid, int areaid, int groupid, string productstring, string pagid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_AddProductsToPromotion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_AddProductsToPromotionResp" +
            "onse")]
        void SQSAdmin_Promotion_AddProductsToPromotion(int multiplepromotionid, string selectedpagid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetAreaInPromotion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetAreaInPromotionResponse" +
            "")]
        System.Data.DataSet SQSAdmin_Promotion_GetAreaInPromotion(int multiplepromotionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetGroupInPromotion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetGroupInPromotionRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_Promotion_GetGroupInPromotion(int multiplepromotionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionForProduct", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionForProductResp" +
            "onse")]
        System.Data.DataSet SQSAdmin_Promotion_GetPromotionForProduct(int pagid, string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetExistingProductsForProm" +
            "otion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetExistingProductsForProm" +
            "otionResponse")]
        System.Data.DataSet SQSAdmin_Promotion_GetExistingProductsForPromotion(int multiplepromotionid, int areaid, int groupid, string productstring, string pagid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionForCopy", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_GetPromotionForCopyRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_Promotion_GetPromotionForCopy(int multiplepromotionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_CopyPromotionProductsFromS" +
            "ourceToTarget", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_CopyPromotionProductsFromS" +
            "ourceToTargetResponse")]
        bool SQSAdmin_Promotion_CopyPromotionProductsFromSourceToTarget(int targetpromotionid, int sourcepromotionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_RemoveProductsFromPromotio" +
            "n", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_RemoveProductsFromPromotio" +
            "nResponse")]
        void SQSAdmin_Promotion_RemoveProductsFromPromotion(int multiplepromotionid, string selectedpagid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_UpdateProductForPromotion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_UpdateProductForPromotionR" +
            "esponse")]
        void SQSAdmin_Promotion_UpdateProductForPromotion(int multiplepromotionid, int pagid, int defaultselected, decimal discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_UpdatePromotion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_Promotion_UpdatePromotionResponse")]
        void SQSAdmin_Promotion_UpdatePromotion(int multiplepromotionid, string baseproduct, decimal promotioncost, decimal capevalue, int forregional, int active, int displaycodeid, string promotionname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetSuppliers", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetSuppliersResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetSuppliers(int stateid, string suppliername, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetActiveQuestions", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetActiveQuestionsResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetActiveQuestions(int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_SearchActiveQuestions", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_SearchActiveQuestionsRespons" +
            "e")]
        System.Data.DataSet SQSAdmin_StudioM_SearchActiveQuestions(int stateid, string searchtext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAnswerForQuestion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAnswerForQuestionResponse" +
            "")]
        System.Data.DataSet SQSAdmin_StudioM_GetAnswerForQuestion(int questionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAvailableGroupListForReta" +
            "ilCluster", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAvailableGroupListForReta" +
            "ilClusterResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetAvailableGroupListForRetailCluster(int retailclusterid, string groupname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetExistingGroupListForRetai" +
            "lCluster", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetExistingGroupListForRetai" +
            "lClusterResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetExistingGroupListForRetailCluster(int retailclusterid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetRetailCluster", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetRetailClusterResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetRetailCluster(int stateid, string clustername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_UpdateProductStudioMAttribut" +
            "e", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_UpdateProductStudioMAttribut" +
            "eResponse")]
        void SQSAdmin_StudioM_UpdateProductStudioMAttribute(string productid, string attribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductStudioMAttribute", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductStudioMAttributeRe" +
            "sponse")]
        string SQSAdmin_StudioM_GetProductStudioMAttribute(string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsSupplierExists", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsSupplierExistsResponse")]
        bool SQSAdmin_StudioM_IsSupplierExists(int stateid, string suppliername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsRetailClusterExists", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsRetailClusterExistsRespons" +
            "e")]
        bool SQSAdmin_StudioM_IsRetailClusterExists(int stateid, string clustername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditRetailCluster", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditRetailClusterResponse" +
            "")]
        void SQSAdmin_StudioM_AddEditRetailCluster(int retailclusterid, string clustername, int stateid, int active, string loginuser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_SaveSelectedGroupToRetailClu" +
            "ster", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_SaveSelectedGroupToRetailClu" +
            "sterResponse")]
        void SQSAdmin_StudioM_SaveSelectedGroupToRetailCluster(int retailclusterid, string selectedgroupid, string usercode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_RemoveSelectedGroupFromRetai" +
            "lCluster", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_RemoveSelectedGroupFromRetai" +
            "lClusterResponse")]
        void SQSAdmin_StudioM_RemoveSelectedGroupFromRetailCluster(int retailclusterid, string selectedgroupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditSupplier", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditSupplierResponse")]
        void SQSAdmin_StudioM_AddEditSupplier(int supplierid, int stateid, string suppliername, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAnswerType", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAnswerTypeResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetAnswerType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetQuestionList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetQuestionListResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetQuestionList(string question, int active, int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsQuestionExists", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsQuestionExistsResponse")]
        bool SQSAdmin_StudioM_IsQuestionExists(int answertypeid, string questiontext, int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditQuestion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditQuestionResponse")]
        void SQSAdmin_StudioM_AddEditQuestion(int questionid, int answertypeid, string questiontext, int active, int mandatory, int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAnswerList", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetAnswerListResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetAnswerList(string questiontext, string answertext, int active, int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsAnswerExists", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_IsAnswerExistsResponse")]
        bool SQSAdmin_StudioM_IsAnswerExists(int questionid, string answertext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditAnswer", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_AddEditAnswerResponse")]
        void SQSAdmin_StudioM_AddEditAnswer(int questionid, int answerid, string answertext, int active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductPrice", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductPriceResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetProductPrice(int stateid, int regionid, string productid, string productname, string productdescription, int active, int studiomproduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductImages", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductImagesResponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetProductImages(string productid, int supplierid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_SaveProductImage", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_SaveProductImageResponse")]
        void SQSAdmin_StudioM_SaveProductImage(string productid, string imagename, int supplierid, byte[] imagestream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_RemoveProductImage", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_RemoveProductImageResponse")]
        void SQSAdmin_StudioM_RemoveProductImage(int imageid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductByCategoryCount", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_GetProductByCategoryCountRes" +
            "ponse")]
        System.Data.DataSet SQSAdmin_StudioM_GetProductByCategoryCount(int stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetStandardInclusi" +
            "onProducts", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetStandardInclusi" +
            "onProductsResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetStandardInclusionProducts(string productid, string proudctname, int stateid, string brandids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetUpgradeOptionBy" +
            "StandardInclusion", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetUpgradeOptionBy" +
            "StandardInclusionResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetUpgradeOptionByStandardInclusion(string productid, string brandids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetAvailableUpgrad" +
            "eOptionProducts", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_GetAvailableUpgrad" +
            "eOptionProductsResponse")]
        System.Data.DataSet SQSAdmin_StandardInclusion_GetAvailableUpgradeOptionProducts(string productid, string proudctname, string brandids, int stateid, string stdinclusionproductid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_RemoveValidationRu" +
            "le", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_RemoveValidationRu" +
            "leResponse")]
        void SQSAdmin_StandardInclusion_RemoveValidationRule(int validationruleid, bool update, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_SaveValidationRule" +
            "", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StandardInclusion_SaveValidationRule" +
            "Response")]
        void SQSAdmin_StandardInclusion_SaveValidationRule(string standardinclusionproductid, string upgradeoptionproductids, string brandids, string usercode, bool promotion, System.DateTime effectivedate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_UpdateStudioMAttributeForClu" +
            "sterOrGroup", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_UpdateStudioMAttributeForClu" +
            "sterOrGroupResponse")]
        void SQSAdmin_StudioM_UpdateStudioMAttributeForClusterOrGroup(string id, string xml, string type, string usercode, string supplieridstring, string questionidstring, string answeridstring, string mandatorystring, string stateid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_LoadStudioMAttributeForClust" +
            "erOrGroup", ReplyAction="http://tempuri.org/ISQSAdminService/SQSAdmin_StudioM_LoadStudioMAttributeForClust" +
            "erOrGroupResponse")]
        System.Data.DataSet SQSAdmin_StudioM_LoadStudioMAttributeForClusterOrGroup(string id, string type, string stateid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISQSAdminServiceChannel : SQSAdmin_WpfCustomControlLibrary.SQSAdminWCFService.ISQSAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQSAdminServiceClient : System.ServiceModel.ClientBase<SQSAdmin_WpfCustomControlLibrary.SQSAdminWCFService.ISQSAdminService>, SQSAdmin_WpfCustomControlLibrary.SQSAdminWCFService.ISQSAdminService {
        
        public SQSAdminServiceClient() {
        }
        
        public SQSAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQSAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQSAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQSAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_LoadSQSGroupList(string groupname) {
            return base.Channel.SQSAdmin_StudioM_LoadSQSGroupList(groupname);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetPAGFromProduct(string productid) {
            return base.Channel.SQSAdmin_StandardInclusion_GetPAGFromProduct(productid);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetRegionGroupByState(int pstateid) {
            return base.Channel.SQSAdmin_StandardInclusion_GetRegionGroupByState(pstateid);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetStandardInclusions(int pbrandid, int pregiongroupid, int pagid, int pstateid, string productid, string productname) {
            return base.Channel.SQSAdmin_StandardInclusion_GetStandardInclusions(pbrandid, pregiongroupid, pagid, pstateid, productid, productname);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetSupplierBrand(string brandname, int pstateid, int active) {
            return base.Channel.SQSAdmin_StudioM_GetSupplierBrand(brandname, pstateid, active);
        }
        
        public void SQSAdmin_StudioM_AddEditSupplierBrand(int supplierbrandid, string brandname, int pstateid, int active, string usercode) {
            base.Channel.SQSAdmin_StudioM_AddEditSupplierBrand(supplierbrandid, brandname, pstateid, active, usercode);
        }
        
        public bool SQSAdmin_StudioM_CheckSupplierBrandExists(string brandname, int pstateid) {
            return base.Channel.SQSAdmin_StudioM_CheckSupplierBrandExists(brandname, pstateid);
        }
        
        public bool SQSAdmin_StandardInclusion_IsStandardInclusionExists(int pagid, int pbrandid, int pregiongroupid, int standardinclusionid) {
            return base.Channel.SQSAdmin_StandardInclusion_IsStandardInclusionExists(pagid, pbrandid, pregiongroupid, standardinclusionid);
        }
        
        public void SQSAdmin_StandardInclusion_AddEditStandardInclusion(int standardinclusionid, int pagid, int pbrandid, int pregiongroupid, decimal quantity, int active, string usercode) {
            base.Channel.SQSAdmin_StandardInclusion_AddEditStandardInclusion(standardinclusionid, pagid, pbrandid, pregiongroupid, quantity, active, usercode);
        }
        
        public void SQSAdmin_StandardInclusion_RemoveStandardInclusion(int standardinclusionid) {
            base.Channel.SQSAdmin_StandardInclusion_RemoveStandardInclusion(standardinclusionid);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetAvailableStandardInclusionPAGFromMasterList(int areaid, int groupid, string productid, string productname, int stateid) {
            return base.Channel.SQSAdmin_StandardInclusion_GetAvailableStandardInclusionPAGFromMasterList(areaid, groupid, productid, productname, stateid);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetAvailableStandardInclusionPAG(int areaid, int groupid, string productid, string productname, int pbrandid, int pregiongroupid) {
            return base.Channel.SQSAdmin_StandardInclusion_GetAvailableStandardInclusionPAG(areaid, groupid, productid, productname, pbrandid, pregiongroupid);
        }
        
        public void SQSAdmin_StandardInclusion_SaveStandardInclusionToBrand(string selectedids, string brandids, int regiongroupid, string usercode, System.DateTime effectivedate) {
            base.Channel.SQSAdmin_StandardInclusion_SaveStandardInclusionToBrand(selectedids, brandids, regiongroupid, usercode, effectivedate);
        }
        
        public System.Data.DataSet SQSAdmin_HomeMinimumArea_GetSourceHomeByBrand(int brandid, string homename) {
            return base.Channel.SQSAdmin_HomeMinimumArea_GetSourceHomeByBrand(brandid, homename);
        }
        
        public System.Data.DataSet SQSAdmin_HomeMinimumArea_GetTargetHomeByBrand(int brandid, string homename) {
            return base.Channel.SQSAdmin_HomeMinimumArea_GetTargetHomeByBrand(brandid, homename);
        }
        
        public void SQSAdmin_HomeMinimumArea_CopyMinimumAreasFromSourceHomeToTargetHome(string sourcehomeid, string targethomeidstring, string usercode) {
            base.Channel.SQSAdmin_HomeMinimumArea_CopyMinimumAreasFromSourceHomeToTargetHome(sourcehomeid, targethomeidstring, usercode);
        }
        
        public void SQSAdmin_StudioM_UploadImageToSharepointImageLibrary(string productid, int supplierid) {
            base.Channel.SQSAdmin_StudioM_UploadImageToSharepointImageLibrary(productid, supplierid);
        }
        
        public System.Data.DataSet SQSAdmin_RelatedArea_LoadProduct(string productid, string keyword, int stateid) {
            return base.Channel.SQSAdmin_RelatedArea_LoadProduct(productid, keyword, stateid);
        }
        
        public System.Data.DataSet SQSAdmin_RelatedArea_LoadExistingAreasForProduct(string productid, int active) {
            return base.Channel.SQSAdmin_RelatedArea_LoadExistingAreasForProduct(productid, active);
        }
        
        public System.Data.DataSet SQSAdmin_RelatedArea_LoadAvailableAreasForProduct(string productid, string keyword, string callfrom) {
            return base.Channel.SQSAdmin_RelatedArea_LoadAvailableAreasForProduct(productid, keyword, callfrom);
        }
        
        public void SQSAdmin_RelatedArea_AddSelectedAreasToProduct(string productid, string areaidstring, string usercode, string callfrom) {
            base.Channel.SQSAdmin_RelatedArea_AddSelectedAreasToProduct(productid, areaidstring, usercode, callfrom);
        }
        
        public void SQSAdmin_RelatedArea_RemooveSelectedAreasFromProduct(string productid, string areaidstring, string callfrom) {
            base.Channel.SQSAdmin_RelatedArea_RemooveSelectedAreasFromProduct(productid, areaidstring, callfrom);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetStudioMProduct(int stateid, string productid, string productname) {
            return base.Channel.SQSAdmin_StudioM_GetStudioMProduct(stateid, productid, productname);
        }
        
        public bool SQSAdmin_StudioM_BulkConfigureStudiomQandA(string supplierbrandid, string productidstring, string questionidstring, string answeridstring, string usercode) {
            return base.Channel.SQSAdmin_StudioM_BulkConfigureStudiomQandA(supplierbrandid, productidstring, questionidstring, answeridstring, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Home_GetHomeList(int stateid, int brandid, string homename, int active) {
            return base.Channel.SQSAdmin_Home_GetHomeList(stateid, brandid, homename, active);
        }
        
        public System.Data.DataSet SQSAdmin_Home_GetHomePlanByStateAndBrands(int stateid, string brandids) {
            return base.Channel.SQSAdmin_Home_GetHomePlanByStateAndBrands(stateid, brandids);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetAreas(int stateid) {
            return base.Channel.SQSAdmin_Generic_GetAreas(stateid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetGroups(int stateid) {
            return base.Channel.SQSAdmin_Generic_GetGroups(stateid);
        }
        
        public System.Data.DataSet SQSAdmin_HomeConfiguration_GetAvailablePAGForHome(int homeid, int areaid, int groupid, string keyword) {
            return base.Channel.SQSAdmin_HomeConfiguration_GetAvailablePAGForHome(homeid, areaid, groupid, keyword);
        }
        
        public System.Data.DataSet SQSAdmin_HomeConfiguration_GetExistingPAGForHome(int homeid, int areaid, int groupid, string keyword) {
            return base.Channel.SQSAdmin_HomeConfiguration_GetExistingPAGForHome(homeid, areaid, groupid, keyword);
        }
        
        public bool SQSAdmin_HomeConfiguration_AddProductToHome(int homeid, string selectedpagid, string qtystring, string changeqtystring, string changepricestring, string extradescstring, string usercode) {
            return base.Channel.SQSAdmin_HomeConfiguration_AddProductToHome(homeid, selectedpagid, qtystring, changeqtystring, changepricestring, extradescstring, usercode);
        }
        
        public bool SQSAdmin_HomeConfiguration_UpdatePagForHome(int homeid, int pagid, string quantity, int changeqty, int changeprice, int extradesc, string usercode) {
            return base.Channel.SQSAdmin_HomeConfiguration_UpdatePagForHome(homeid, pagid, quantity, changeqty, changeprice, extradesc, usercode);
        }
        
        public bool SQSAdmin_HomeConfiguration_RemoveProductsFromHome(int homeid, string selectedpagids, string usercode) {
            return base.Channel.SQSAdmin_HomeConfiguration_RemoveProductsFromHome(homeid, selectedpagids, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_HomeConfiguration_GetProducts(int stateid, string productid, string keyword) {
            return base.Channel.SQSAdmin_HomeConfiguration_GetProducts(stateid, productid, keyword);
        }
        
        public string SQSAdmin_HomeConfiguration_CopyProductConfiguration(string sourceproductid, string targetproductid, string usercode) {
            return base.Channel.SQSAdmin_HomeConfiguration_CopyProductConfiguration(sourceproductid, targetproductid, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_QuantityManagement_GetHomeModelQuantity(string stateid, string areaid, string groupid, string brandid) {
            return base.Channel.SQSAdmin_QuantityManagement_GetHomeModelQuantity(stateid, areaid, groupid, brandid);
        }
        
        public System.Data.DataSet SQSAdmin_QuantityManagement_GetHomeFacadeQuantity(string stateid, string areaid, string groupid, string brandid) {
            return base.Channel.SQSAdmin_QuantityManagement_GetHomeFacadeQuantity(stateid, areaid, groupid, brandid);
        }
        
        public bool SQSAdmin_QuantityManagement_UpdateQuantityForAreaGroupAtHomeModel(string stateid, string areaid, string groupid, string brandid, string homemodel, string quantity, string usercode) {
            return base.Channel.SQSAdmin_QuantityManagement_UpdateQuantityForAreaGroupAtHomeModel(stateid, areaid, groupid, brandid, homemodel, quantity, usercode);
        }
        
        public bool SQSAdmin_QuantityManagement_UpdateQuantityForAreaGroupAtHomeFacade(string areaid, string groupid, string homeid, string quantity, string usercode) {
            return base.Channel.SQSAdmin_QuantityManagement_UpdateQuantityForAreaGroupAtHomeFacade(areaid, groupid, homeid, quantity, usercode);
        }
        
        public bool SQSAdmin_QuantityManagement_RefreshQuantity(string stateid, string areaid, string groupid, string usercode) {
            return base.Channel.SQSAdmin_QuantityManagement_RefreshQuantity(stateid, areaid, groupid, usercode);
        }
        
        public bool SQSAdmin_HomeConfiguration_BulkUpdateQuantity(string homeid, string pagidstring, string quantity, string usercode) {
            return base.Channel.SQSAdmin_HomeConfiguration_BulkUpdateQuantity(homeid, pagidstring, quantity, usercode);
        }
        
        public bool SQSAdmin_HomeConfiguration_BulkUpdateHomeModelQuantity(string brandid, string areaid, string groupid, string homestring, string quantity, string usercode) {
            return base.Channel.SQSAdmin_HomeConfiguration_BulkUpdateHomeModelQuantity(brandid, areaid, groupid, homestring, quantity, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_SearchDisclaimers(int typeid, int stateid, int regionid, int brandid) {
            return base.Channel.SQSAdmin_SearchDisclaimers(typeid, stateid, regionid, brandid);
        }
        
        public string SQSAdmin_SearchDisclaimer(string type, string state, int regionid, int brandid, string brandname, System.DateTime depositDate) {
            return base.Channel.SQSAdmin_SearchDisclaimer(type, state, regionid, brandid, brandname, depositDate);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_BasePriceHoldDays(string stateid, string regionids, string brandids, System.DateTime effectivedate, string active) {
            return base.Channel.SQSAdmin_Generic_BasePriceHoldDays(stateid, regionids, brandids, effectivedate, active);
        }
        
        public void SQSAdmin_Generic_UpdateBasePriceHoldDays(string id, string daysfrom, string daysto, System.DateTime effectivedate, string active, string depositamount, string usercode, decimal cmapercent, decimal surchargepercent, decimal btpsinglestorey, decimal btpdoublestorey, decimal btpSingleStoryDiscount, decimal btpDoubleStoryDiscount, decimal btpSingleStoreyCostSiteOther, decimal btpDoubleStoreyCostSiteOther) {
            base.Channel.SQSAdmin_Generic_UpdateBasePriceHoldDays(id, daysfrom, daysto, effectivedate, active, depositamount, usercode, cmapercent, surchargepercent, btpsinglestorey, btpdoublestorey, btpSingleStoryDiscount, btpDoubleStoryDiscount, btpSingleStoreyCostSiteOther, btpDoubleStoreyCostSiteOther);
        }
        
        public void SQSAdmin_Generic_NeweBasePriceHoldDays(
                    int stateid, 
                    string regionids, 
                    string brandids, 
                    string daysfrom, 
                    string daysto, 
                    System.DateTime effectivedate, 
                    string active, 
                    string depositamount, 
                    string usercode, 
                    string cmapercent, 
                    string surchargepercent, 
                    string regionalsurchargeSSpercent, 
                    string regionalsurchargeSDpercent, 
                    string btpSingleStoryDiscount, 
                    string btpDoubleStoryDiscount, 
                    string btpSingleStoreyCostSiteOther, 
                    string btpDoubleStoreyCostSiteOther) {
            base.Channel.SQSAdmin_Generic_NeweBasePriceHoldDays(stateid, regionids, brandids, daysfrom, daysto, effectivedate, active, depositamount, usercode, cmapercent, surchargepercent, regionalsurchargeSSpercent, regionalsurchargeSDpercent, btpSingleStoryDiscount, btpDoubleStoryDiscount, btpSingleStoreyCostSiteOther, btpDoubleStoreyCostSiteOther);
        }
        
        public string SQSAdmin_SaveDisclaimer(string type, string state, string regionids, string brandids, string disclaimerText, string internalNotes, string effectiveDate, int status, string usercode) {
            return base.Channel.SQSAdmin_SaveDisclaimer(type, state, regionids, brandids, disclaimerText, internalNotes, effectiveDate, status, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetState() {
            return base.Channel.SQSAdmin_Generic_GetState();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetRegionList(int stateid) {
            return base.Channel.SQSAdmin_Generic_GetRegionList(stateid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetAllAreas() {
            return base.Channel.SQSAdmin_Generic_GetAllAreas();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetAllGroups() {
            return base.Channel.SQSAdmin_Generic_GetAllGroups();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetGroupsFromArea(int areaid) {
            return base.Channel.SQSAdmin_Generic_GetGroupsFromArea(areaid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetBrandByState(int stateid) {
            return base.Channel.SQSAdmin_Generic_GetBrandByState(stateid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetHomeNameBySearch(int stateid, int brandid, string homename) {
            return base.Channel.SQSAdmin_Generic_GetHomeNameBySearch(stateid, brandid, homename);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetSQSConfiguration(string configCode, string codeValue) {
            return base.Channel.SQSAdmin_Generic_GetSQSConfiguration(configCode, codeValue);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetSpecificationByStateRegionsBrands(int stateid, string regionids, string brandids, System.DateTime effdate, string systemid, string attachmentid, string homestring) {
            return base.Channel.SQSAdmin_Generic_GetSpecificationByStateRegionsBrands(stateid, regionids, brandids, effdate, systemid, attachmentid, homestring);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetSpecificationByStateRegionBrand(int stateid, int regionid, int brandid, System.DateTime effdate, string systemid, string attachmentid, string homestring) {
            return base.Channel.SQSAdmin_Generic_GetSpecificationByStateRegionBrand(stateid, regionid, brandid, effdate, systemid, attachmentid, homestring);
        }
        
        public void SQSAdmin_Generic_SaveSpecificationByStateRegionBrand(int id, string filename, int stateid, int regionid, int brandid, int homeid, System.DateTime effdate, int systemformid, int attachmenttypeid, int active) {
            base.Channel.SQSAdmin_Generic_SaveSpecificationByStateRegionBrand(id, filename, stateid, regionid, brandid, homeid, effdate, systemformid, attachmenttypeid, active);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetAvailabeAreasByHome(int homeid) {
            return base.Channel.SQSAdmin_Generic_GetAvailabeAreasByHome(homeid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetConfiguredAreasByHome(int homeid) {
            return base.Channel.SQSAdmin_Generic_GetConfiguredAreasByHome(homeid);
        }
        
        public void SQSAdmin_Generic_AddMinimumAreasToHome(int homeid, string selectedareaid, string usercode) {
            base.Channel.SQSAdmin_Generic_AddMinimumAreasToHome(homeid, selectedareaid, usercode);
        }
        
        public void SQSAdmin_Generic_RemoveMinimumAreasFromHome(int homeid, string selectedareaid, string usercode) {
            base.Channel.SQSAdmin_Generic_RemoveMinimumAreasFromHome(homeid, selectedareaid, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetAvailablePAGByState(string stateid, string areaid, string groupid, string keyword, string pagid) {
            return base.Channel.SQSAdmin_Generic_GetAvailablePAGByState(stateid, areaid, groupid, keyword, pagid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetDisplayHomeByPAGAndState(string stateid, string brandid, string pagid, string displayhomename, string suburb) {
            return base.Channel.SQSAdmin_Generic_GetDisplayHomeByPAGAndState(stateid, brandid, pagid, displayhomename, suburb);
        }
        
        public string SQSAdmin_Generic_ReplaceDisplayHomePAG(string existingpagid, string newpagid, string displayhomeid, string usercode, string qty, string changeqty, string changeprice, string allowdesc, string desc, string newextradesc) {
            return base.Channel.SQSAdmin_Generic_ReplaceDisplayHomePAG(existingpagid, newpagid, displayhomeid, usercode, qty, changeqty, changeprice, allowdesc, desc, newextradesc);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetProductUOM() {
            return base.Channel.SQSAdmin_Generic_GetProductUOM();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetProductCategory() {
            return base.Channel.SQSAdmin_Generic_GetProductCategory();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetProductCode() {
            return base.Channel.SQSAdmin_Generic_GetProductCode();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetProductDisplayCode(string forpromo) {
            return base.Channel.SQSAdmin_Generic_GetProductDisplayCode(forpromo);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_GetProductCostCenterCode() {
            return base.Channel.SQSAdmin_Generic_GetProductCostCenterCode();
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ImportProduct(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ImportProduct(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ImportPriceVerticalFormat(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ImportPriceVerticalFormat(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ImportPriceHorizontalFormat(System.Data.DataTable dt, string usercode, string stateid) {
            return base.Channel.SQSAdmin_Generic_ImportPriceHorizontalFormat(dt, usercode, stateid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ImportPriceHorizontalFormatNSW(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ImportPriceHorizontalFormatNSW(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ImportQuantity(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ImportQuantity(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_CheckExistingProducts(System.Data.DataTable dt) {
            return base.Channel.SQSAdmin_Generic_CheckExistingProducts(dt);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ValidatePriceVerticalFormat(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ValidatePriceVerticalFormat(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ValidatePriceHorizontalFormat(System.Data.DataTable dt, string usercode, string stateid) {
            return base.Channel.SQSAdmin_Generic_ValidatePriceHorizontalFormat(dt, usercode, stateid);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ValidatePriceHorizontalFormatNSW(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ValidatePriceHorizontalFormatNSW(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Generic_ValidateQuantity(System.Data.DataTable dt, string usercode) {
            return base.Channel.SQSAdmin_Generic_ValidateQuantity(dt, usercode);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetPromotionList(int stateid, int brandid, int storey, int status) {
            return base.Channel.SQSAdmin_Promotion_GetPromotionList(stateid, brandid, storey, status);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetPromotionTypeList() {
            return base.Channel.SQSAdmin_Promotion_GetPromotionTypeList();
        }
        
        public bool SQSAdmin_Promotion_UpdateMultiplePromotionName(string promotionid, string promotionname) {
            return base.Channel.SQSAdmin_Promotion_UpdateMultiplePromotionName(promotionid, promotionname);
        }
        
        public bool SQSAdmin_Promotion_CheckMasterPromotionProductExist(int stateid, string productid) {
            return base.Channel.SQSAdmin_Promotion_CheckMasterPromotionProductExist(stateid, productid);
        }
        
        public bool SQSAdmin_Promotion_CheckMultiplePromotionExist(int brandid, int stories, string productid) {
            return base.Channel.SQSAdmin_Promotion_CheckMultiplePromotionExist(brandid, stories, productid);
        }
        
        public void SQSAdmin_Promotion_SavePromotion(int stateid, int brandid, int storey, int promotiontypeid, string productid, string promotionname, decimal promotioncost, decimal capevalue, int forregional, int active, int displaycodeid) {
            base.Channel.SQSAdmin_Promotion_SavePromotion(stateid, brandid, storey, promotiontypeid, productid, promotionname, promotioncost, capevalue, forregional, active, displaycodeid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetPromotionDetails(int multiplepromotionid) {
            return base.Channel.SQSAdmin_Promotion_GetPromotionDetails(multiplepromotionid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetAvailableProductsForPromotion(int multiplepromotionid, int areaid, int groupid, string productstring, string pagid) {
            return base.Channel.SQSAdmin_Promotion_GetAvailableProductsForPromotion(multiplepromotionid, areaid, groupid, productstring, pagid);
        }
        
        public void SQSAdmin_Promotion_AddProductsToPromotion(int multiplepromotionid, string selectedpagid) {
            base.Channel.SQSAdmin_Promotion_AddProductsToPromotion(multiplepromotionid, selectedpagid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetAreaInPromotion(int multiplepromotionid) {
            return base.Channel.SQSAdmin_Promotion_GetAreaInPromotion(multiplepromotionid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetGroupInPromotion(int multiplepromotionid) {
            return base.Channel.SQSAdmin_Promotion_GetGroupInPromotion(multiplepromotionid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetPromotionForProduct(int pagid, string productid) {
            return base.Channel.SQSAdmin_Promotion_GetPromotionForProduct(pagid, productid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetExistingProductsForPromotion(int multiplepromotionid, int areaid, int groupid, string productstring, string pagid) {
            return base.Channel.SQSAdmin_Promotion_GetExistingProductsForPromotion(multiplepromotionid, areaid, groupid, productstring, pagid);
        }
        
        public System.Data.DataSet SQSAdmin_Promotion_GetPromotionForCopy(int multiplepromotionid) {
            return base.Channel.SQSAdmin_Promotion_GetPromotionForCopy(multiplepromotionid);
        }
        
        public bool SQSAdmin_Promotion_CopyPromotionProductsFromSourceToTarget(int targetpromotionid, int sourcepromotionid) {
            return base.Channel.SQSAdmin_Promotion_CopyPromotionProductsFromSourceToTarget(targetpromotionid, sourcepromotionid);
        }
        
        public void SQSAdmin_Promotion_RemoveProductsFromPromotion(int multiplepromotionid, string selectedpagid) {
            base.Channel.SQSAdmin_Promotion_RemoveProductsFromPromotion(multiplepromotionid, selectedpagid);
        }
        
        public void SQSAdmin_Promotion_UpdateProductForPromotion(int multiplepromotionid, int pagid, int defaultselected, decimal discount) {
            base.Channel.SQSAdmin_Promotion_UpdateProductForPromotion(multiplepromotionid, pagid, defaultselected, discount);
        }
        
        public void SQSAdmin_Promotion_UpdatePromotion(int multiplepromotionid, string baseproduct, decimal promotioncost, decimal capevalue, int forregional, int active, int displaycodeid, string promotionname) {
            base.Channel.SQSAdmin_Promotion_UpdatePromotion(multiplepromotionid, baseproduct, promotioncost, capevalue, forregional, active, displaycodeid, promotionname);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetSuppliers(int stateid, string suppliername, int active) {
            return base.Channel.SQSAdmin_StudioM_GetSuppliers(stateid, suppliername, active);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetActiveQuestions(int stateid) {
            return base.Channel.SQSAdmin_StudioM_GetActiveQuestions(stateid);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_SearchActiveQuestions(int stateid, string searchtext) {
            return base.Channel.SQSAdmin_StudioM_SearchActiveQuestions(stateid, searchtext);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetAnswerForQuestion(int questionid) {
            return base.Channel.SQSAdmin_StudioM_GetAnswerForQuestion(questionid);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetAvailableGroupListForRetailCluster(int retailclusterid, string groupname) {
            return base.Channel.SQSAdmin_StudioM_GetAvailableGroupListForRetailCluster(retailclusterid, groupname);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetExistingGroupListForRetailCluster(int retailclusterid) {
            return base.Channel.SQSAdmin_StudioM_GetExistingGroupListForRetailCluster(retailclusterid);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetRetailCluster(int stateid, string clustername) {
            return base.Channel.SQSAdmin_StudioM_GetRetailCluster(stateid, clustername);
        }
        
        public void SQSAdmin_StudioM_UpdateProductStudioMAttribute(string productid, string attribute) {
            base.Channel.SQSAdmin_StudioM_UpdateProductStudioMAttribute(productid, attribute);
        }
        
        public string SQSAdmin_StudioM_GetProductStudioMAttribute(string productid) {
            return base.Channel.SQSAdmin_StudioM_GetProductStudioMAttribute(productid);
        }
        
        public bool SQSAdmin_StudioM_IsSupplierExists(int stateid, string suppliername) {
            return base.Channel.SQSAdmin_StudioM_IsSupplierExists(stateid, suppliername);
        }
        
        public bool SQSAdmin_StudioM_IsRetailClusterExists(int stateid, string clustername) {
            return base.Channel.SQSAdmin_StudioM_IsRetailClusterExists(stateid, clustername);
        }
        
        public void SQSAdmin_StudioM_AddEditRetailCluster(int retailclusterid, string clustername, int stateid, int active, string loginuser) {
            base.Channel.SQSAdmin_StudioM_AddEditRetailCluster(retailclusterid, clustername, stateid, active, loginuser);
        }
        
        public void SQSAdmin_StudioM_SaveSelectedGroupToRetailCluster(int retailclusterid, string selectedgroupid, string usercode) {
            base.Channel.SQSAdmin_StudioM_SaveSelectedGroupToRetailCluster(retailclusterid, selectedgroupid, usercode);
        }
        
        public void SQSAdmin_StudioM_RemoveSelectedGroupFromRetailCluster(int retailclusterid, string selectedgroupid) {
            base.Channel.SQSAdmin_StudioM_RemoveSelectedGroupFromRetailCluster(retailclusterid, selectedgroupid);
        }
        
        public void SQSAdmin_StudioM_AddEditSupplier(int supplierid, int stateid, string suppliername, int active) {
            base.Channel.SQSAdmin_StudioM_AddEditSupplier(supplierid, stateid, suppliername, active);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetAnswerType() {
            return base.Channel.SQSAdmin_StudioM_GetAnswerType();
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetQuestionList(string question, int active, int stateid) {
            return base.Channel.SQSAdmin_StudioM_GetQuestionList(question, active, stateid);
        }
        
        public bool SQSAdmin_StudioM_IsQuestionExists(int answertypeid, string questiontext, int stateid) {
            return base.Channel.SQSAdmin_StudioM_IsQuestionExists(answertypeid, questiontext, stateid);
        }
        
        public void SQSAdmin_StudioM_AddEditQuestion(int questionid, int answertypeid, string questiontext, int active, int mandatory, int stateid) {
            base.Channel.SQSAdmin_StudioM_AddEditQuestion(questionid, answertypeid, questiontext, active, mandatory, stateid);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetAnswerList(string questiontext, string answertext, int active, int stateid) {
            return base.Channel.SQSAdmin_StudioM_GetAnswerList(questiontext, answertext, active, stateid);
        }
        
        public bool SQSAdmin_StudioM_IsAnswerExists(int questionid, string answertext) {
            return base.Channel.SQSAdmin_StudioM_IsAnswerExists(questionid, answertext);
        }
        
        public void SQSAdmin_StudioM_AddEditAnswer(int questionid, int answerid, string answertext, int active) {
            base.Channel.SQSAdmin_StudioM_AddEditAnswer(questionid, answerid, answertext, active);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetProductPrice(int stateid, int regionid, string productid, string productname, string productdescription, int active, int studiomproduct) {
            return base.Channel.SQSAdmin_StudioM_GetProductPrice(stateid, regionid, productid, productname, productdescription, active, studiomproduct);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetProductImages(string productid, int supplierid) {
            return base.Channel.SQSAdmin_StudioM_GetProductImages(productid, supplierid);
        }
        
        public void SQSAdmin_StudioM_SaveProductImage(string productid, string imagename, int supplierid, byte[] imagestream) {
            base.Channel.SQSAdmin_StudioM_SaveProductImage(productid, imagename, supplierid, imagestream);
        }
        
        public void SQSAdmin_StudioM_RemoveProductImage(int imageid) {
            base.Channel.SQSAdmin_StudioM_RemoveProductImage(imageid);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_GetProductByCategoryCount(int stateid) {
            return base.Channel.SQSAdmin_StudioM_GetProductByCategoryCount(stateid);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetStandardInclusionProducts(string productid, string proudctname, int stateid, string brandids) {
            return base.Channel.SQSAdmin_StandardInclusion_GetStandardInclusionProducts(productid, proudctname, stateid, brandids);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetUpgradeOptionByStandardInclusion(string productid, string brandids) {
            return base.Channel.SQSAdmin_StandardInclusion_GetUpgradeOptionByStandardInclusion(productid, brandids);
        }
        
        public System.Data.DataSet SQSAdmin_StandardInclusion_GetAvailableUpgradeOptionProducts(string productid, string proudctname, string brandids, int stateid, string stdinclusionproductid) {
            return base.Channel.SQSAdmin_StandardInclusion_GetAvailableUpgradeOptionProducts(productid, proudctname, brandids, stateid, stdinclusionproductid);
        }
        
        public void SQSAdmin_StandardInclusion_RemoveValidationRule(int validationruleid, bool update, bool active) {
            base.Channel.SQSAdmin_StandardInclusion_RemoveValidationRule(validationruleid, update, active);
        }
        
        public void SQSAdmin_StandardInclusion_SaveValidationRule(string standardinclusionproductid, string upgradeoptionproductids, string brandids, string usercode, bool promotion, System.DateTime effectivedate) {
            base.Channel.SQSAdmin_StandardInclusion_SaveValidationRule(standardinclusionproductid, upgradeoptionproductids, brandids, usercode, promotion, effectivedate);
        }
        
        public void SQSAdmin_StudioM_UpdateStudioMAttributeForClusterOrGroup(string id, string xml, string type, string usercode, string supplieridstring, string questionidstring, string answeridstring, string mandatorystring, string stateid) {
            base.Channel.SQSAdmin_StudioM_UpdateStudioMAttributeForClusterOrGroup(id, xml, type, usercode, supplieridstring, questionidstring, answeridstring, mandatorystring, stateid);
        }
        
        public System.Data.DataSet SQSAdmin_StudioM_LoadStudioMAttributeForClusterOrGroup(string id, string type, string stateid) {
            return base.Channel.SQSAdmin_StudioM_LoadStudioMAttributeForClusterOrGroup(id, type, stateid);
        }
    }
}
