# This is a basic workflow to help you get started with Actions

name: RSM Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # get the branch nam
  brname:
    runs-on: ubuntu-latest
    outputs:
      bname: ${{ steps.extract_branch.outputs.branch }}
      
    steps:
    - id: extract_branch 
      shell: bash
      run: (echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})" && (echo ${GITHUB_EVENT_NAME}|grep 'push')) || (echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF##*/})" && (echo ${GITHUB_EVENT_NAME}|grep 'pull_request'))

  # This workflow contains a single job called "build"
  build:
    env:
      filename: SQSAdmin-${{ needs.brname.outputs.bname }}-${{ github.run_id }}.zip

    needs: brname
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    # Build
    - name: MSBuild publish (SQS Admin) # Using profile (which might need extra treament to be character escaped, e.g. quotes, etc)
      run: msbuild $env:Solution_Path -p:Configuration=Release -p:DeployOnBuild=True  -p:IgnoreDeployManagedRuntimeVersion=True 
      env:
        Solution_Path: SQSAdmin\SQSAdmin.csproj          

    - name: Archive package
      shell: powershell
      run: |
        Compress-Archive -Path SQSAdmin\bin\release\*.* -Destination SQSAdmin\SQSAdmin-${{ needs.brname.outputs.bname }}-${{ github.run_id }}.zip

    # Upload the  package
    - name: Upload SQS Admin build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SQS Admin Package ${{ needs.brname.outputs.bname }} ${{ github.run_id }} 
        path: SQSAdmin\SQSAdmin-${{ needs.brname.outputs.bname }}-${{ github.run_id }}.zip            

    # Build
    #- name: MSBuild publish (SQS WCF Admin) # Using profile (which might need extra treament to be character escaped, e.g. quotes, etc)
    #  run: msbuild $env:Solution_Path -p:Configuration=Release -p:DeployOnBuild=True -p:PackageAsSingleFile=true -p:IgnoreDeployManagedRuntimeVersion=True -p:PackageFileName=$env:TargetPkgFileName                   
    #  env:
    #    Solution_Path: SQSAdminWCFService\SQSAdminWCFService.csproj      
    #    TargetPkgFileName: SQSAdminWCF-${{ needs.brname.outputs.bname }}-${{ github.run_id }}.zip   

    # Upload the  package 
    #- name: Upload SQS WCF ADmin build artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: SQS Admin WCF Package ${{ needs.brname.outputs.bname }} ${{ github.run_id }} 
    #    path: SQSAdminWCFService\SQSAdminWCF-${{ needs.brname.outputs.bname }}-${{ github.run_id }}.*                 